"""Compatibility accounting for processors retired by the P2 safety boundary.

Each node ID is deliberately listed instead of marking an entire module. These
historical tests assert detailed behavior of processors that now fail closed;
the dedicated tombstone tests assert the stable error contract and zero side
effects. strict=True makes an unexpected processor resurrection a suite
failure rather than silently accepting it.
"""

from __future__ import annotations

import pytest

_RETIRED_PROCESSOR_COMPATIBILITY_NODEIDS = frozenset(
    {
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_confidence_is_055",
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_does_not_break_clean_layers",
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_on_handles_sparse_input",
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_on_yields_at_least_as_many_polygons_as_off",
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_shape_off_matches_v051",
        "tests/test_alpha_shape.py::test_polygonize_layer_alpha_shape_on_uses_alpha_shape_rung",
        "tests/test_apply_marked_content.py::test_apply_cli_architectural_uses_marked_content_layer_overrides",
        "tests/test_apply_marked_content.py::test_apply_uses_marked_content_ocg_layer_to_override_color_mapping",
        "tests/test_apply_marked_content.py::test_apply_warns_and_falls_back_when_marked_content_is_unbalanced",
        "tests/test_apply_marked_content.py::test_apply_warns_and_falls_back_when_marked_content_property_is_missing",
        "tests/test_apply_jsx_bugs.py::test_apply_via_jsx_rejects_error_report",
        "tests/test_apply_jsx_bugs.py::test_apply_via_jsx_rejects_missing_output_after_report",
        "tests/test_apply_saas_no_payload.py::test_apply_saas_no_numblock_points_to_alternative",
        "tests/test_apply_saas_no_payload.py::test_apply_saas_no_numblock_raises_clean_error",
        "tests/test_apply_saas_no_payload.py::test_apply_saas_poche_no_numblock_raises_clean_error",
        "tests/test_apply_saas_no_payload.py::test_apply_saas_cli_no_numblock_raises_click_exception",
        "tests/test_apply_saas_poche.py::test_apply_saas_with_poche_can_write_overlay_layer_without_env",
        "tests/test_apply_saas_poche.py::test_apply_saas_with_poche_end_to_end_on_synthetic_fixture",
        "tests/test_apply_saas_poche.py::test_apply_saas_with_poche_rejects_same_src_dst",
        "tests/test_apply_saas_poche.py::test_enumerate_handles_curves_via_endpoint_approximation",
        "tests/test_apply_saas_poche.py::test_enumerate_ignores_text_setup_before_real_layer",
        "tests/test_apply_saas_poche.py::test_enumerate_layer_paths_picks_up_stroked_segments",
        "tests/test_apply_saas_poche.py::test_inspect_falls_back_to_private_payload_cmyk_colors",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_does_not_fill_visible_only_timber_targets",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_fills_visible_foundation_footing_without_rebar_symbols",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_injects_marked_clt_slab_bands",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_keeps_marked_backup_wall_cap_above_concrete_stem",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_keeps_timber_tabs_at_cut_width_when_helpers_are_wider",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_preserves_marked_clt_slab_gap",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_promotes_low_confidence_concrete_when_completion_is_anchored",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_recovers_fragmented_c2_c3_concrete_edges",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_rejects_visible_foundation_column_stem",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_uses_roof_helpers_for_open_cut_roof",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_uses_same_component_helpers_without_filling_them",
        "tests/test_apply_saas_poche.py::test_polygonize_dump_uses_structural_completion_for_timber_helpers",
        "tests/test_architectural_mode.py::test_polygonize_reports_structural_open_loop_when_bridge_fails",
        "tests/test_architectural_mode.py::test_polygonize_uses_helper_tangents_to_close_parallel_structural_edges",
        "tests/test_architectural_mode.py::test_structural_open_loop_can_add_missing_regions_to_existing_closed_loops",
        "tests/test_architectural_mode.py::test_structural_open_loop_closes_tiny_collinear_fragment_gaps",
        "tests/test_architectural_mode.py::test_structural_open_loop_keeps_larger_collinear_void_open",
        "tests/test_basic.py::test_hatch_concrete_returns_lines",
        "tests/test_basic.py::test_hatch_register_custom_material",
        "tests/test_basic.py::test_hatch_solid_materials_return_empty",
        "tests/test_basic.py::test_hatch_unknown_material_raises",
        "tests/test_basic.py::test_inspect_dispatches_to_pikepdf_for_ai_extension",
        "tests/test_basic.py::test_inspect_pikepdf_path_tracks_q_Q_state",
        "tests/test_basic.py::test_inspect_routes_pdf_extension_to_pymupdf_path",
        "tests/test_basic.py::test_inspect_unreadable_file_raises_with_workaround_hint",
        "tests/test_basic.py::test_poche_polygonize_layer_falls_back_for_disconnected",
        "tests/test_basic.py::test_poche_polygonize_layer_returns_failed_for_empty",
        "tests/test_basic.py::test_poche_polygonize_layer_works_on_closed_polyline",
        "tests/test_basic.py::test_poche_user_override_skip",
        "tests/test_basic.py::test_poisson_disk_safety_cap",
        "tests/test_bridge_strategy.py::test_best_at_least_matches_greedy_polygon_count",
        "tests/test_bridge_strategy.py::test_env_var_greedy_still_routes_to_legacy_bridger",
        "tests/test_bridge_strategy.py::test_env_var_greedy_threads_through_polygonize_layer",
        "tests/test_bridge_strategy.py::test_env_var_threads_through_polygonize_layer",
        "tests/test_bridge_strategy.py::test_fill_result_bridge_strategy_name_set_when_best_wins",
        "tests/test_bridge_strategy.py::test_fill_result_bridge_strategy_name_unset_when_explicit_greedy",
        "tests/test_bridge_strategy.py::test_polygonize_layer_best_calls_strategy_selector",
        "tests/test_bridge_strategy.py::test_polygonize_layer_best_respects_endpoint_cap",
        "tests/test_bridge_strategy.py::test_polygonize_layer_default_calls_best_selector",
        "tests/test_bridge_strategy.py::test_polygonize_layer_default_output_matches_best",
        "tests/test_bridge_strategy.py::test_polygonize_layer_explicit_greedy_still_calls_legacy_bridger",
        "tests/test_cleanup.py::test_cleanup_cli_writes_new_file_and_json_report",
        "tests/test_bridge_rhino_ai.py::test_cli_bridge_rhino_ai_dry_run_plans_layout_apply_and_poche",
        "tests/test_bridge_rhino_ai.py::test_cli_bridge_rhino_ai_failure_is_nonzero_and_points_to_report",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_requires_apply_before_poche",
        "tests/test_bridge_rhino_ai.py::test_cli_bridge_rhino_ai_threads_options_to_orchestrator",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_apply_failure_writes_stage_report",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_dry_run_plans_layout_apply_and_poche_without_gui",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_rejects_apply_jsx_error_report_even_with_output",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_rejects_apply_jsx_missing_hierarchy_output",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_runs_apply_then_poche_on_layout_output",
        "tests/test_bridge_rhino_ai.py::test_bridge_rhino_ai_writes_failed_report_when_layout_stage_raises",
        "tests/test_bridge_strategy.py::test_cli_poche_threads_strategy_to_apply_poche",
        "tests/test_bridge_strategy.py::test_cli_poche_default_threads_best",
        "tests/test_bridge_strategy.py::test_cli_poche_explicit_greedy_threads_legacy",
        "tests/test_layout_jsx.py::test_cli_layout_jsx_threads_options_to_runner",
        "tests/test_layout_jsx.py::test_cli_layout_jsx_rejects_bad_artboard",
        "tests/test_layout_jsx.py::test_cli_layout_jsx_failure_is_nonzero_without_wrote_claim",
        "tests/test_layout_jsx.py::test_layout_converted_doc_after_open_mismatch_fails_with_report",
        "tests/test_layout_jsx.py::test_layout_converted_doc_exact_path_reports_open_doc_without_review",
        "tests/test_layout_jsx.py::test_layout_converted_doc_pathless_stem_match_reports_needs_review",
        "tests/test_layout_jsx.py::test_layout_detects_converted_doc_after_open_and_rerenders_open_doc_jsx",
        "tests/test_layout_jsx.py::test_layout_dry_run_does_not_probe_illustrator",
        "tests/test_layout_jsx.py::test_layout_real_run_failed_report_raises_and_normalizes",
        "tests/test_layout_jsx.py::test_layout_real_run_missing_report_raises",
        "tests/test_layout_jsx.py::test_layout_real_run_normalizes_illustrator_report_to_stable_schema",
        "tests/test_layout_jsx.py::test_layout_real_run_passed_report_without_output_raises",
        "tests/test_poche_report_json.py::test_cli_poche_writes_structured_report_json",
        "tests/test_poche_report_json.py::test_cli_poche_threads_geometry_json_path",
        "tests/test_run_report.py::test_poche_cli_writes_durable_report",
        "tests/test_cli_input_preflight.py::test_apply_blank_pdf_with_mapping_fails_before_noop_output",
        "tests/test_cli_input_preflight.py::test_apply_malformed_input_fails_cleanly_without_traceback",
        "tests/test_cli_input_preflight.py::test_apply_postscript_ai_fails_before_parser_traceback",
        "tests/test_cli_input_preflight.py::test_inspect_blank_plain_pdf_reports_non_drawing_diagnostic",
        "tests/test_cli_input_preflight.py::test_inspect_empty_layer_aware_ai_has_different_empty_export_message",
        "tests/test_cli_input_preflight.py::test_inspect_postscript_ai_returns_machine_readable_diagnostic",
        "tests/test_cli_input_preflight.py::test_inspect_zip_header_mismatch_reports_unsupported_input",
        "tests/test_cli_proof_check.py::test_proof_check_can_materialize_public_synthetic_packet",
        "tests/test_cli_proof_check.py::test_proof_check_expected_fail_does_not_mask_no_go",
        "tests/test_cli_proof_check.py::test_proof_check_expected_fail_unexpected_pass_is_failed",
        "tests/test_cli_proof_check.py::test_proof_check_fails_when_manifest_expected_counts_do_not_match_report",
        "tests/test_cli_proof_check.py::test_proof_check_fails_when_rendered_views_are_effectively_unchanged",
        "tests/test_cli_proof_check.py::test_proof_check_fails_when_report_json_is_missing",
        "tests/test_cli_proof_check.py::test_proof_check_materialize_synthetic_does_not_clear_private_manual_review",
        "tests/test_cli_proof_check.py::test_proof_check_materializes_public_synthetic_sentinels",
        "tests/test_cli_proof_check.py::test_proof_check_plan_only_reads_make2d_manifest_and_emits_packet_plan",
        "tests/test_cli_proof_check.py::test_proof_check_unsupported_requires_explicit_evidence",
        "tests/test_cli_proof_check.py::test_proof_check_validates_existing_packet_and_writes_json",
        "tests/test_depth_grading.py::test_inspect_surfaces_depth_source_from_layer_metadata",
        "tests/test_drawing_type.py::test_apply_dry_run_names_inferred_type_and_selected_preset",
        "tests/test_drawing_type.py::test_inspect_report_surfaces_drawing_type",
        "tests/test_hatch_v05.py::test_board_formed_concrete_has_horizontal_seams",
        "tests/test_hatch_v05.py::test_cmu_on_empty_polygon",
        "tests/test_hatch_v05.py::test_cmu_on_tiny_polygon",
        "tests/test_hatch_v05.py::test_cmu_produces_geometry",
        "tests/test_hatch_v05.py::test_polyiso_distinct_from_generic_rigid",
        "tests/test_hatch_v05.py::test_standing_seam_copper_has_vertical_seams",
        "tests/test_hatch_v05.py::test_stucco_produces_dense_stipple",
        "tests/test_legacy_postscript_error.py::test_inspect_legacy_postscript_raises_actionable_error",
        "tests/test_llm_topology.py::test_cost_reporting_debug_on",
        "tests/test_llm_topology.py::test_infer_respects_model_env_var",
        "tests/test_llm_topology.py::test_infer_truncates_large_anchor_lists",
        "tests/test_llm_topology.py::test_infer_uses_default_model_when_not_overridden",
        "tests/test_llm_topology.py::test_infer_uses_prompt_caching_on_system_prompt",
        "tests/test_llm_topology.py::test_infer_uses_tool_use_for_strict_json",
        "tests/test_llm_topology.py::test_infer_with_injected_client_returns_plan",
        "tests/test_llm_topology.py::test_polygonize_layer_skips_llm_rung_when_gate_off",
        "tests/test_llm_topology.py::test_polygonize_layer_skips_llm_when_no_api_key",
        "tests/test_llm_topology.py::test_polygonize_layer_skips_to_concave_when_llm_returns_useless_plan",
        "tests/test_llm_topology.py::test_polygonize_layer_uses_llm_rung_when_geometric_fail",
        "tests/test_proof.py::test_assert_handoff_is_public_safe_rejects_local_path_in_json",
        "tests/test_proof.py::test_committed_manifest_review_region_can_fail_synthetic_packet",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-acceptance_recorded must be false]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-local/private path references]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-overlay template must not claim visual acceptance]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-posting_ready must be false]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-private fixture tokens]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-public_clearance must be NO-GO]",
        "tests/test_proof.py::test_find_handoff_public_safety_violations_rejects_overclaims[<lambda>-public_safe must be false]",
        "tests/test_proof.py::test_helper_backed_concrete_poche_report_stays_review_gated_in_proof",
        "tests/test_proof.py::test_validate_proof_packet_accepts_solid_region_with_strict_ratio_and_delta",
        "tests/test_proof.py::test_validate_proof_packet_accepts_w5_w7_visual_layer_gate",
        "tests/test_proof.py::test_validate_proof_packet_checks_dark_pixels_in_matching_review_region",
        "tests/test_proof.py::test_validate_proof_packet_fails_when_matching_review_region_stays_light",
        "tests/test_proof.py::test_validate_proof_packet_fails_when_review_region_has_no_matching_rendered_view",
        "tests/test_proof.py::test_validate_proof_packet_is_public_safe_only_with_w5_w7_acceptance",
        "tests/test_proof.py::test_validate_proof_packet_needs_review_for_visual_acceptance_gate",
        "tests/test_proof.py::test_validate_proof_packet_passes_clean_report_but_is_not_public_safe_without_acceptance",
        "tests/test_proof.py::test_validate_proof_packet_rejects_effectively_unchanged_rendered_views_when_enabled",
        "tests/test_proof.py::test_validate_proof_packet_rejects_local_paths_and_sanitizes_public_summary",
        "tests/test_proof.py::test_validate_proof_packet_rejects_missing_artifacts",
        "tests/test_proof.py::test_validate_proof_packet_rejects_no_go_report",
        "tests/test_proof.py::test_validate_proof_packet_rejects_no_go_summary_status",
        "tests/test_proof.py::test_validate_proof_packet_rejects_sparse_outline_when_region_requires_solid_poche",
        "tests/test_proof.py::test_validate_proof_packet_requires_dark_delta_from_before_view",
        "tests/test_proof.py::test_validate_proof_packet_requires_full_board_and_closeup_views",
        "tests/test_proof.py::test_validate_proof_packet_requires_report_identity_and_rendered_views",
        "tests/test_proof.py::test_validate_proof_packet_visual_acceptance_does_not_clear_non_visual_review",
        "tests/test_proof.py::test_validate_proof_packet_visual_acceptance_requires_allowed_reviewer_and_exact_layer",
        "tests/test_proof.py::test_w5_w7_handoff_stays_no_go_when_packet_passed_but_not_public_safe",
        "tests/test_proof.py::test_w5_w7_handoff_zip_contains_public_safe_files",
        "tests/test_proof.py::test_write_w5_w7_handoff_to_zip_rejects_local_path_in_markdown",
        "tests/test_v1_integration.py::test_apply_auto_role_cut_at_least_as_heavy_as_legacy",
        "tests/test_v1_integration.py::test_apply_auto_role_default_writes_role_weights",
        "tests/test_v1_integration.py::test_apply_twice_does_not_compound_widths",
        "tests/test_v1_integration.py::test_auto_by_role_axon_reuses_elevation_weights",
        "tests/test_v1_integration.py::test_auto_by_role_darkest_color_is_the_cut",
        "tests/test_v1_integration.py::test_cli_apply_accepts_axon_preset_and_matches_elevation_bytes",
        "tests/test_v1_integration.py::test_cli_color_coded_board_does_not_warn",
        "tests/test_v1_integration.py::test_cli_no_strict_warns_but_exits_0",
        "tests/test_v1_integration.py::test_cli_warns_and_exits_2_on_single_color",
        "tests/test_v1_integration.py::test_cli_warns_and_exits_2_on_zero_stroke",
        "tests/test_v1_integration.py::test_dash_emitted_for_dashed_linetype",
        "tests/test_v1_integration.py::test_dash_pattern_does_not_leak_to_other_strokes",
        "tests/test_v1_integration.py::test_inspect_surfaces_aia_per_layer_plan",
        "tests/test_v1_integration.py::test_legacy_weights_pins_to_luminance_output",
        "tests/test_v1_integration.py::test_no_linetype_arg_is_byte_identical",
        "tests/test_v1_integration.py::test_non_plotting_is_counted_not_deleted",
    }
)


def pytest_collection_modifyitems(items: list[pytest.Item]) -> None:
    """When freeze is on, mark historical processor tests as expected failures."""
    from arch_line_weights.safety import freeze_legacy_apply_enabled

    if not freeze_legacy_apply_enabled():
        return
    for item in items:
        if item.nodeid in _RETIRED_PROCESSOR_COMPATIBILITY_NODEIDS:
            item.add_marker(
                pytest.mark.xfail(
                    strict=True,
                    reason=(
                        "P2 compatibility: ARCH_LW_FREEZE_LEGACY_APPLY is set, so this "
                        "historical assertion exercises a fail-closed processor; "
                        "test_processing_tombstones owns its fail-closed contract."
                    ),
                )
            )
